version: '3.1'

services:

  cms:
    container_name: lc-boilerplate-cms
    image: ghost:3-alpine
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://cms.lc-boilerplate.local:8080
    volumes:
      - ./.storage/ghost-content:/var/lib/ghost/content
    networks: 
      default:
        aliases: 
          - cms.lc-boilerplate.local

  db:
    container_name: lc-boilerplate-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./.storage/data:/var/lib/mysql
    networks: 
      - default

  frontend:
    container_name: lc-boilerplate-frontend
    depends_on: 
      - db
      - cms
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    networks: 
      - default
    
networks:
  default:
